-- AlterTable
ALTER TABLE "Children" ALTER COLUMN "userBabyHeight" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "userBabyWeight" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "userBabyHead" SET DATA TYPE DECIMAL(65,30);
